USE Gestion_Vente_DB

CREATE TABLE CATEGORIE
(
	ID_CAT INT,
	DESCRIPTION_CAT VARCHAR(50),
	CONSTRAINT PK_CATEGORIE PRIMARY KEY(ID_CAT)
)

CREATE TABLE PRODUIT
(
	ID_PRODUIT INT,
	ID_CAT INT,
	NOM_PRODUIT VARCHAR(40),
	QTE_STOCK INT,
	PRIX VARCHAR(25),
	IMG_PRODUIT IMAGE,
	CONSTRAINT PK_PRODUIT PRIMARY KEY(ID_PRODUIT),
	CONSTRAINT FK_CATEGORIE FOREIGN KEY(ID_CAT) REFERENCES CATEGORIE(ID_CAT)
)

CREATE TABLE CLIENT
(
	ID_CLIENT INT IDENTITY(1, 1),
	CITY_ID INT,
	NOM_CLIENT VARCHAR(30),
	PRN_CLIENT VARCHAR(30),
	TEL_CLIENT INT,
	EMAIL VARCHAR(50),
	IMAGE_CLIENT IMAGE,
	CONSTRAINT PK_CLIENT PRIMARY KEY(ID_CLIENT),
	CONSTRAINT FK_CITY FOREIGN KEY(CITY_ID) REFERENCES CITY(CITY_ID)
)


CREATE TABLE COMMANDE
(
	ID_CMD INT,
	ID_CLIENT INT,
	DATE_CMD DATE,
	DESCRIPTION_CMD VARCHAR(250),
	NOM_VENDU VARCHAR(75),
	CONSTRAINT PK_COMMANDE PRIMARY KEY(ID_CMD),
	CONSTRAINT FK_CLIENT FOREIGN KEY(ID_CLIENT) REFERENCES CLIENT(ID_CLIENT)
)

CREATE TABLE DETAIL_CMD
(
	ID_PRODUIT INT,
	ID_CMD INT,
	QUANTITE INT,
	PRICE MONEY,
	DISCOUNT FLOAT,
	AMOUNT VARCHAR(50),
	TOTAL_AMOUNT VARCHAR(50),
	CONSTRAINT PK_PRODUIT_COMMANDE PRIMARY KEY(ID_PRODUIT, ID_CMD),
	CONSTRAINT FK_PRODUIT FOREIGN KEY(ID_PRODUIT) REFERENCES PRODUIT(ID_PRODUIT),
	CONSTRAINT FK_COMMANDE FOREIGN KEY(ID_CMD) REFERENCES COMMANDE(ID_CMD)
)


CREATE TABLE CITY
(
	CITY_ID INT IDENTITY(1, 1),
	CITY_NAME VARCHAR(50),
	CONSTRAINT PK_CITY PRIMARY KEY(CITY_ID)
)


CREATE TABLE USERS
(
	USERNAME VARCHAR(50),
	PSW VARCHAR(50),
	USERTYPE VARCHAR(50),
	CONSTRAINT PK_USERS PRIMARY KEY(USERNAME)
)

INSERT INTO USERS VALUES('admin', 'ad123', 'administrator');
INSERT INTO USERS VALUES('Mojahid', 'mo123', 'user');
INSERT INTO USERS VALUES('Kamal', 'ka123', 'user');

SELECT * FROM USERS
